// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlZbNBldwjx3hJqf8_-7ksrakGnITCpQ4',
    appId: '1:1097842554330:web:c915bb21733ab0b2c77ce3',
    messagingSenderId: '1097842554330',
    projectId: 'seo-ai-mastermind',
    authDomain: 'seo-ai-mastermind.firebaseapp.com',
    storageBucket: 'seo-ai-mastermind.firebasestorage.app',
    measurementId: 'G-2EG62FZT6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm_j2hOocnqeLZVEGwN-9_HeSiHPzZI8o',
    appId: '1:1097842554330:android:1e272ce6bc7ff832c77ce3',
    messagingSenderId: '1097842554330',
    projectId: 'seo-ai-mastermind',
    storageBucket: 'seo-ai-mastermind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBUvxwXLP1pHrFEiwCcJskfaittVtwjQ',
    appId: '1:1097842554330:ios:be982c40fe34e7c0c77ce3',
    messagingSenderId: '1097842554330',
    projectId: 'seo-ai-mastermind',
    storageBucket: 'seo-ai-mastermind.firebasestorage.app',
    iosBundleId: 'com.example.seoAiMastermind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjBUvxwXLP1pHrFEiwCcJskfaittVtwjQ',
    appId: '1:1097842554330:ios:be982c40fe34e7c0c77ce3',
    messagingSenderId: '1097842554330',
    projectId: 'seo-ai-mastermind',
    storageBucket: 'seo-ai-mastermind.firebasestorage.app',
    iosBundleId: 'com.example.seoAiMastermind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlZbNBldwjx3hJqf8_-7ksrakGnITCpQ4',
    appId: '1:1097842554330:web:ec03813927eacb04c77ce3',
    messagingSenderId: '1097842554330',
    projectId: 'seo-ai-mastermind',
    authDomain: 'seo-ai-mastermind.firebaseapp.com',
    storageBucket: 'seo-ai-mastermind.firebasestorage.app',
    measurementId: 'G-9K9W0YGET1',
  );
}
